### ISSUE TITLE
Timeout not long enough

### ISSUE THREAD

**Issue by zeenix** [openshift/cluster-machine-approver#36]
Ever since d7e76c48c4f29e7bef109e6aed5d400c0e6cbd4b, the CSR on not-so-fast hosts (e.g nested-virt) [don't get auto-approved any more](https://github.com/openshift/installer/issues/1893) and people have to manually approve them for cluster to initialize. After an enlightening discussion with the commit author @enj, I'm not sure what can be done in the short term for this but we have to fix this sooner or later somehow.

**Comment by zeenix** [comment]
Independent report of this on baremetal: https://bugzilla.redhat.com/show_bug.cgi?id=1723955

**Comment by cgwalters** [comment]
I think if we tied together the MCO and machine API more, we could have the MCO inject a per-machine secret into the cloud-init data provided, tied to the machine resource.  This would give us a way for booted nodes to prove their identity, and CSR approval could be tied to that.  There wouldn't be any need for timeouts (or, they could be way, way longer because we're not worried about machine reuse).

**Comment by enj** [comment]
> I think if we tied together the MCO and machine API more, we could have the MCO inject a per-machine secret into the cloud-init data provided, tied to the machine resource. This would give us a way for booted nodes to prove their identity, and CSR approval could be tied to that. There wouldn't be any need for timeouts (or, they could be way, way longer because we're not worried about machine reuse).

+100

The current approach is just meant as a series of probabilities that reduce the impact of lost bootstrap credentials.  With proper cryptographic node attestation, the timing and abuse checks simply disappear as we can easily determine the identity of a node.

**Comment by russellb** [comment]
The approach of using per-machine secrets sounds great.

> Independent report of this on baremetal: https://bugzilla.redhat.com/show_bug.cgi?id=1723955

In this issue, it occurs on AWS with a bare metal instance type.  This problem will also come up for the `baremetal` infrastructure platform type, where we're automating the provisioning of bare metal hosts.  It can take more than 10 minutes for a server to boot.  When automating provisioning on prem, we'll have a minimum of two boots to wait for.

**Comment by cgwalters** [comment]
The tricky thing about this is that in a machineAPI managed environment, we control the whole stack and are in a position to do lots of sophisticated things.  But in e.g. a bare metal PXE environment (non-metalkube), we don't really have a programmatic way to inject data into the booted machines.   On the other hand, I think in a "manual bare metal" env you really end up needing/wanting to manually approve CSRs anyways.

**Comment by russellb** [comment]
> The tricky thing about this is that in a machineAPI managed environment, we control the whole stack and are in a position to do lots of sophisticated things. But in e.g. a bare metal PXE environment (non-metalkube), we don't really have a programmatic way to inject data into the booted machines. On the other hand, I think in a "manual bare metal" env you really end up needing/wanting to manually approve CSRs anyways.

Yeah, I think in a manual provisioning environment, manual approval of CSRs seems reasonable to me.

**Comment by cgwalters** [comment]
See https://github.com/openshift/machine-config-operator/pull/759 which was some prep work on this I started.

**Comment by michaelgugino** [comment]
While I think having another component deal with injecting the token into the pointer-ignition would be a better architecture if we started with this, it presents some problems for existing deployments.

First, we can't guarantee that each machine is using the same user-data secret as it's set on a per-machine basis.  Further, it's set as part of the providerSpec and not a high-level config in the machine-api proper (though we can probably work around this with interface{} magic, but seems not ideal long-term as it's yet-another-place we need to integrate future providers).

We could use one-time tokens, or we could use crypographic hash, something like 'shared-secret'+'machine-name'. 

Either way, I think the machine-controller is the right place to do the user-data/ignition injection.  We can just look for ```my-machine-token``` that gets created by the MCO.  We discussed this approach previously in slack.  This would be pretty much transparent to all existing deployments (except BYO workers, they'll need to sort out authentication to ignition (maybe basic auth?)

**Comment by mhrivnak** [comment]
It looks like there are [six checks](https://github.com/openshift/cluster-machine-approver/blob/d7e76c48c4f29e7bef109e6aed5d400c0e6cbd4b/csr_check.go#L107-L118) to make a "best-effort" assessment. They are:

1. User is the node bootstrapper
2. Node does not exist
3. Use machine API internal DNS to locate matching machine based on node name
4. Machine must not have a node ref
5. CSR creation timestamp is very close to machine creation timestamp
6. CSR is meant for node client auth based on usage, CN, etc

The timestamp check may not be as useful or reliable as hoped. If the intent of that check is to prevent re-use of leaked credentials, perhaps there's a better way to detect that.

For example, could we replace the timestamp check with a check of the machine's [phase](https://github.com/kubernetes-sigs/cluster-api/blob/835ee87/pkg/apis/cluster/v1alpha2/machine_types.go#L154-L157)? Perhaps require that the phase is "Provisioning". Or require that the phase is not "Provisioned", "Deleted", etc. That would be a more direct way to evaluate if the machine really is still trying to provision, rather than making assumptions about how much time provisioning should take.

It's possible that some providers are not currently setting the phase, so that could be a limiting factor. Or maybe they set the phase to "Provisioned" before the Node successfully joins. But if this check is important enough that it's worth adding behavior to providers, I'd rather have providers set the phase accordingly than have providers estimate a timeout value for their environment.

**Comment by michaelgugino** [comment]
> It looks like there are [six checks](https://github.com/openshift/cluster-machine-approver/blob/d7e76c48c4f29e7bef109e6aed5d400c0e6cbd4b/csr_check.go#L107-L118) to make a "best-effort" assessment. They are:
> 
>     1. User is the node bootstrapper
> 
>     2. Node does not exist
> 
>     3. Use machine API internal DNS to locate matching machine based on node name
> 
>     4. Machine must not have a node ref
> 
>     5. CSR creation timestamp is very close to machine creation timestamp
> 
>     6. CSR is meant for node client auth based on usage, CN, etc
> 
> 
> The timestamp check may not be as useful or reliable as hoped. If the intent of that check is to prevent re-use of leaked credentials, perhaps there's a better way to detect that.
> 
> For example, could we replace the timestamp check with a check of the machine's [phase](https://github.com/kubernetes-sigs/cluster-api/blob/835ee87/pkg/apis/cluster/v1alpha2/machine_types.go#L154-L157)? Perhaps require that the phase is "Provisioning". Or require that the phase is not "Provisioned", "Deleted", etc. That would be a more direct way to evaluate if the machine really is still trying to provision, rather than making assumptions about how much time provisioning should take.
> 
> It's possible that some providers are not currently setting the phase, so that could be a limiting factor. Or maybe they set the phase to "Provisioned" before the Node successfully joins. But if this check is important enough that it's worth adding behavior to providers, I'd rather have providers set the phase accordingly than have providers estimate a timeout value for their environment.

I don't really want to put more emphasis on what the machine object is doing or what 'state' it's in.  The presence or absence of nodeRef is the only 'state' we care about.  I'm hoping to get rid of the 'state' altogether or rather, simplify it to: 
1) You have a machine object with no instance, 
2) you have a machine-object with an instance irrespective of that instance's state, 
3) you have a noderef.

The best way to prevent forged CSR requests is to lock-down the token used to generate a CSR request.  In order to lock that down, we have to lock down ignition.  We also don't want to put username/password for ignition into user data (even though that would be better than what we have today) as far as I can tell, thus the one-time token.

**Comment by mhrivnak** [comment]
> I don't really want to put more emphasis on what the machine object is doing or what 'state' it's in. The presence or absence of nodeRef is the only 'state' we care about. 

Great. Then perhaps we can just stop checking the machine's creation timestamp?

> The best way to prevent forged CSR requests is to lock-down the token used to generate a CSR request.

I'm completely on-board with that. I'm just thinking of what we can do in the meantime (not sure how long that will take to implement) so we don't have to estimate timeouts.

**Comment by michaelgugino** [comment]
> > I don't really want to put more emphasis on what the machine object is doing or what 'state' it's in. The presence or absence of nodeRef is the only 'state' we care about.
> 
> Great. Then perhaps we can just stop checking the machine's creation timestamp?
> 
> > The best way to prevent forged CSR requests is to lock-down the token used to generate a CSR request.
> 
> I'm completely on-board with that. I'm just thinking of what we can do in the meantime (not sure how long that will take to implement) so we don't have to estimate timeouts.

@mhrivnak I'm for removing the creation-timestamp check (other than ensure CSR comes *after*, but without a time limit), but I'm facing resistance for bumping it to 20 minutes!  I wanted to do 24 hours, or even 6 hours, but so far no dice on my end.  I'm not sure who I need to convince.
